// --------------------------------------------------------------------------------
// Copyright (c) 2026 Aspose.Words for Cloud
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// --------------------------------------------------------------------------------

use std::collections::HashMap;

use async_trait::async_trait;
use chrono::{DateTime, Utc};

use crate::models::*;
use crate::responses::*;
use crate::request::{
    ApiRequestData, DynamicResponse, ProgressCallback, Request, ResponseData, TypedRequest,
};
use crate::{ApiClient, SdkResult};
use super::*;

/// Request parameters for the ExecuteMailMerge operation.
pub struct ExecuteMailMergeRequest {
    /// The filename of the input document.
    pub r#name: String,
    /// Mail merge data.
    pub r#data: Option<String>,
    /// Field options.
    pub r#options: Option<FieldOptions>,
    /// Original document folder.
    pub r#folder: Option<String>,
    /// Original document storage.
    pub r#storage: Option<String>,
    /// Encoding that will be used to load an HTML (or TXT) document if the encoding is not specified in HTML.
    pub r#load_encoding: Option<String>,
    /// Password of protected Word document. Use the parameter to pass a password via SDK. SDK encrypts it automatically. We don't recommend to use the parameter to pass a plain password for direct call of API.
    pub r#password: Option<String>,
    /// Password of protected Word document. Use the parameter to pass an encrypted password for direct calls of API. See SDK code for encyption details.
    pub r#encrypted_password: Option<String>,
    /// The value indicates whether OpenType support is on.
    pub r#open_type_support: Option<bool>,
    /// The flag indicating whether to execute Mail Merge operation with regions.
    pub r#with_regions: Option<bool>,
    /// The data file.
    pub r#mail_merge_data_file: Option<String>,
    /// The cleanup options.
    pub r#cleanup: Option<String>,
    /// The flag indicating whether paragraph with TableStart or TableEnd field should be fully included into mail merge region or particular range between TableStart and TableEnd fields. The default value is true.
    pub r#use_whole_paragraph_as_region: Option<bool>,
    /// The flag indicating whether fields in whole document are updated while executing of a mail merge with regions.
    pub r#merge_whole_document: Option<bool>,
    /// The filename of the output document. If this parameter is omitted, the result will be saved with autogenerated name.
    pub r#dest_file_name: Option<String>,
    pub send_progress: Option<ProgressCallback>,
    pub receive_progress: Option<ProgressCallback>,
}

impl ExecuteMailMergeRequest {
    pub fn new(r#name: String) -> Self {
        Self {
            r#name,
            r#data: None,
            r#options: None,
            r#folder: None,
            r#storage: None,
            r#load_encoding: None,
            r#password: None,
            r#encrypted_password: None,
            r#open_type_support: None,
            r#with_regions: None,
            r#mail_merge_data_file: None,
            r#cleanup: None,
            r#use_whole_paragraph_as_region: None,
            r#merge_whole_document: None,
            r#dest_file_name: None,
            send_progress: None,
            receive_progress: None,
        }
    }

    pub fn with_data(mut self, value: String) -> Self {
        self.r#data = Some(value);
        self
    }

    pub fn with_options(mut self, value: FieldOptions) -> Self {
        self.r#options = Some(value);
        self
    }

    pub fn with_folder(mut self, value: String) -> Self {
        self.r#folder = Some(value);
        self
    }

    pub fn with_storage(mut self, value: String) -> Self {
        self.r#storage = Some(value);
        self
    }

    pub fn with_load_encoding(mut self, value: String) -> Self {
        self.r#load_encoding = Some(value);
        self
    }

    pub fn with_password(mut self, value: String) -> Self {
        self.r#password = Some(value);
        self
    }

    pub fn with_encrypted_password(mut self, value: String) -> Self {
        self.r#encrypted_password = Some(value);
        self
    }

    pub fn with_open_type_support(mut self, value: bool) -> Self {
        self.r#open_type_support = Some(value);
        self
    }

    pub fn with_with_regions(mut self, value: bool) -> Self {
        self.r#with_regions = Some(value);
        self
    }

    pub fn with_mail_merge_data_file(mut self, value: String) -> Self {
        self.r#mail_merge_data_file = Some(value);
        self
    }

    pub fn with_cleanup(mut self, value: String) -> Self {
        self.r#cleanup = Some(value);
        self
    }

    pub fn with_use_whole_paragraph_as_region(mut self, value: bool) -> Self {
        self.r#use_whole_paragraph_as_region = Some(value);
        self
    }

    pub fn with_merge_whole_document(mut self, value: bool) -> Self {
        self.r#merge_whole_document = Some(value);
        self
    }

    pub fn with_dest_file_name(mut self, value: String) -> Self {
        self.r#dest_file_name = Some(value);
        self
    }

    pub fn with_send_progress(mut self, callback: ProgressCallback) -> Self {
        self.send_progress = Some(callback);
        self
    }

    pub fn with_receive_progress(mut self, callback: ProgressCallback) -> Self {
        self.receive_progress = Some(callback);
        self
    }

    async fn parse_response_data(response: ResponseData) -> SdkResult<DocumentResponse> {
        Ok(serde_json::from_slice::<DocumentResponse>(&response.body)?)
    }

}

#[async_trait]
impl TypedRequest for ExecuteMailMergeRequest {
    type Response = DocumentResponse;

    async fn parse_response(&self, response: ResponseData) -> SdkResult<Self::Response> {
        Self::parse_response_data(response).await
    }
}

#[async_trait]
impl Request for ExecuteMailMergeRequest {
    async fn build(&self, client: &ApiClient) -> SdkResult<ApiRequestData> {
        let mut path = "/words/{name}/MailMerge".to_owned();
        let mut query = Vec::new();
        let mut headers = Vec::new();
        let mut body_parts = Vec::new();

        let value = client.query_value(&self.r#name)?;
        path = path.replace("{name}", &value);
        if let Some(value) = &self.r#folder {
        query.push(("folder".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#storage {
        query.push(("storage".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#load_encoding {
        query.push(("loadEncoding".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#password {
        query.push(("encryptedPassword".to_owned(), client.encrypt_password(value).await?));
        }
        if let Some(value) = &self.r#encrypted_password {
        query.push(("encryptedPassword".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#open_type_support {
        query.push(("openTypeSupport".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#with_regions {
        query.push(("withRegions".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#mail_merge_data_file {
        query.push(("mailMergeDataFile".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#cleanup {
        query.push(("cleanup".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#use_whole_paragraph_as_region {
        query.push(("useWholeParagraphAsRegion".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#merge_whole_document {
        query.push(("mergeWholeDocument".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#dest_file_name {
        query.push(("destFileName".to_owned(), client.query_value(value)?));
        }
        if let Some(value) = &self.r#data {
        client.add_text_part(&mut body_parts, "Data", value);
        }
        if let Some(value) = &self.r#options {
        client.add_model_part(&mut body_parts, "Options", value).await?;
        }

        let url = client.build_url(&path, &query)?;
        let body = client.request_body_from_parts(&mut headers, body_parts);
        Ok(ApiRequestData {
            method: reqwest::Method::PUT,
            url,
            headers,
            body,
            send_progress: self.send_progress.clone(),
            receive_progress: self.receive_progress.clone(),
        })
    }

    async fn parse_any(&self, response: ResponseData) -> SdkResult<DynamicResponse> {
        Ok(Box::new(Self::parse_response_data(response).await?))
    }
}