// --------------------------------------------------------------------------------
// Copyright (c) 2026 Aspose.Words for Cloud
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// --------------------------------------------------------------------------------

use std::any::Any;
use std::ops::{Deref, DerefMut};

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::{SdkError, SdkResult};

use super::*;

/// Container class for html save options.
#[derive(Debug, Deserialize, Serialize)]
pub struct HtmlSaveOptionsData {
    #[serde(flatten)]
    pub parent: SaveOptionsData,
        /// Gets or sets a value indicating whether negative left and right indents of paragraphs are allowed (not normalized).
        #[serde(rename = "AllowNegativeIndent", skip_serializing_if = "Option::is_none")]
        pub r#allow_negative_indent: Option<bool>,


        /// Gets or sets the prefix which is added to all CSS class names. The default value is an empty string and generated CSS class names have no common prefix.
            /// If this value is not empty, all CSS classes generated by Aspose.Words will start with the specified prefix.This might be useful, for example, if you add custom CSS to generated documents and want to prevent class name conflicts.
            /// If the value is not null or empty, it must be a valid CSS identifier.
        #[serde(rename = "CssClassNamePrefix", skip_serializing_if = "Option::is_none")]
        pub r#css_class_name_prefix: Option<String>,


        /// Gets or sets the name of the CSS file written when the document is exported to HTML.
        #[serde(rename = "CssStyleSheetFileName", skip_serializing_if = "Option::is_none")]
        pub r#css_style_sheet_file_name: Option<String>,


        /// Gets or sets the option that controls how the CSS styles are exported.
        #[serde(rename = "CssStyleSheetType", skip_serializing_if = "Option::is_none")]
        pub r#css_style_sheet_type: Option<HtmlSaveOptionsData_CssStyleSheetTypeEnum>,


        /// Gets or sets the option that controls how the document should be split when saving.
        #[serde(rename = "DocumentSplitCriteria", skip_serializing_if = "Option::is_none")]
        pub r#document_split_criteria: Option<HtmlSaveOptionsData_DocumentSplitCriteriaEnum>,


        /// Gets or sets the maximum level of headings at which to split the document.
        #[serde(rename = "DocumentSplitHeadingLevel", skip_serializing_if = "Option::is_none")]
        pub r#document_split_heading_level: Option<i32>,


        /// Gets or sets the character encoding to use when exporting.
        #[serde(rename = "Encoding", skip_serializing_if = "Option::is_none")]
        pub r#encoding: Option<String>,


        /// Gets or sets a value indicating whether to export built-in and custom document properties.
        #[serde(rename = "ExportDocumentProperties", skip_serializing_if = "Option::is_none")]
        pub r#export_document_properties: Option<bool>,


        /// Gets or sets the flag, that controls how drop-down form fields are saved to HTML.
            /// The default value is false.
            /// When set to true, exports drop-down form fields as normal text.
            /// When false, exports drop-down form fields as SELECT element in HTML.
        #[serde(rename = "ExportDropDownFormFieldAsText", skip_serializing_if = "Option::is_none")]
        pub r#export_drop_down_form_field_as_text: Option<bool>,


        /// Gets or sets a value indicating whether font resources should be exported.
        #[serde(rename = "ExportFontResources", skip_serializing_if = "Option::is_none")]
        pub r#export_font_resources: Option<bool>,


        /// Gets or sets a value indicating whether fonts resources should be embedded to HTML in Base64 encoding. The default value is false.
        #[serde(rename = "ExportFontsAsBase64", skip_serializing_if = "Option::is_none")]
        pub r#export_fonts_as_base64: Option<bool>,


        /// Gets or sets the option that controls how headers and footers are exported.
        #[serde(rename = "ExportHeadersFootersMode", skip_serializing_if = "Option::is_none")]
        pub r#export_headers_footers_mode: Option<HtmlSaveOptionsData_ExportHeadersFootersModeEnum>,


        /// Gets or sets a value indicating whether images are saved in Base64 format.
        #[serde(rename = "ExportImagesAsBase64", skip_serializing_if = "Option::is_none")]
        pub r#export_images_as_base64: Option<bool>,


        /// Gets or sets a value indicating whether language information is exported.
        #[serde(rename = "ExportLanguageInformation", skip_serializing_if = "Option::is_none")]
        pub r#export_language_information: Option<bool>,


        /// Gets or sets the option that controls how list labels are exported.
        #[serde(rename = "ExportListLabels", skip_serializing_if = "Option::is_none")]
        pub r#export_list_labels: Option<HtmlSaveOptionsData_ExportListLabelsEnum>,


        /// Gets or sets a value indicating whether the original URL should be used as the URL of the linked images.
            /// The default value is false.
            /// If value is set to true - ResourceFolder value is used as the URL of linked images and linked images are not loaded into document's folder or ImagesFolder.If value is set to false - linked images are loaded into document's folder or ImagesFolder and URL of each linked image is constructed depending on document's folder, ImagesFolder and ImagesFolderAlias properties.
        #[serde(rename = "ExportOriginalUrlForLinkedImages", skip_serializing_if = "Option::is_none")]
        pub r#export_original_url_for_linked_images: Option<bool>,


        /// Gets or sets a value indicating whether page margins are exported to HTML, MHTML or EPUB.
            /// The default value is false.
            /// Aspose.Words does not show the area of page margins by default. If any elements are completely or partially clipped by the document edge the displayed area can be extended with this option.
        #[serde(rename = "ExportPageMargins", skip_serializing_if = "Option::is_none")]
        pub r#export_page_margins: Option<bool>,


        /// Gets or sets a value indicating whether page setup is exported.
        #[serde(rename = "ExportPageSetup", skip_serializing_if = "Option::is_none")]
        pub r#export_page_setup: Option<bool>,


        /// Gets or sets a value indicating whether font sizes should be output in relative units when saving.
        #[serde(rename = "ExportRelativeFontSize", skip_serializing_if = "Option::is_none")]
        pub r#export_relative_font_size: Option<bool>,


        /// Gets or sets a value indicating whether to write the roundtrip information when saving to HTML. The default value is true.
            /// Saving of the roundtrip information allows to restore document properties such as tab stops, comments, headers and footers during the HTML documents loading back into a Document object.When true, the roundtrip information is exported as -aw-* CSS properties of the corresponding HTML elements.When false, causes no roundtrip information to be output into produced files.
        #[serde(rename = "ExportRoundtripInformation", skip_serializing_if = "Option::is_none")]
        pub r#export_roundtrip_information: Option<bool>,


        /// Gets or sets the flag, that controls how text input form fields are saved.
        #[serde(rename = "ExportTextInputFormFieldAsText", skip_serializing_if = "Option::is_none")]
        pub r#export_text_input_form_field_as_text: Option<bool>,


        /// Gets or sets a value indicating whether to write page numbers to table of contents when saving.
        #[serde(rename = "ExportTocPageNumbers", skip_serializing_if = "Option::is_none")]
        pub r#export_toc_page_numbers: Option<bool>,


        /// Gets or sets a value indicating whether to write the DOCTYPE declaration when saving.
        #[serde(rename = "ExportXhtmlTransitional", skip_serializing_if = "Option::is_none")]
        pub r#export_xhtml_transitional: Option<bool>,


        /// Gets or sets the option that controls which font resources need subsetting when saving.
        #[serde(rename = "FontResourcesSubsettingSizeThreshold", skip_serializing_if = "Option::is_none")]
        pub r#font_resources_subsetting_size_threshold: Option<i32>,


        /// Gets or sets the physical folder where fonts are saved when exporting a document.
        #[serde(rename = "FontsFolder", skip_serializing_if = "Option::is_none")]
        pub r#fonts_folder: Option<String>,


        /// Gets or sets the name of the folder used to construct font URIs.
        #[serde(rename = "FontsFolderAlias", skip_serializing_if = "Option::is_none")]
        pub r#fonts_folder_alias: Option<String>,


        /// Gets or sets the version of HTML standard, that should be used when saving the document to HTML or MHTML.
            /// The default value is Aspose.Words.Saving.HtmlVersion.Xhtml.
        #[serde(rename = "HtmlVersion", skip_serializing_if = "Option::is_none")]
        pub r#html_version: Option<HtmlSaveOptionsData_HtmlVersionEnum>,


        /// Gets or sets the output resolution for images when exporting.
        #[serde(rename = "ImageResolution", skip_serializing_if = "Option::is_none")]
        pub r#image_resolution: Option<i32>,


        /// Gets or sets the physical folder where images are saved when exporting a document.
        #[serde(rename = "ImagesFolder", skip_serializing_if = "Option::is_none")]
        pub r#images_folder: Option<String>,


        /// Gets or sets the name of the folder used to construct image URIs.
        #[serde(rename = "ImagesFolderAlias", skip_serializing_if = "Option::is_none")]
        pub r#images_folder_alias: Option<String>,


        /// Gets or sets the options, that controls in what format metafiles are saved when exporting to HTML, MHTML, or EPUB.
            /// The default value is Aspose.Words.Saving.HtmlMetafileFormat.Png, meaning that metafiles are rendered to raster PNG images.
            /// Metafiles are not natively displayed by HTML browsers. By default, Aspose.Words converts WMF and EMF images into PNG files when exporting to HTML.Other options are to convert metafiles to SVG images or to export them as is without conversion.
            /// Some image transforms, in particular image cropping, will not be applied to metafile images if they are exported to HTML without conversion.
        #[serde(rename = "MetafileFormat", skip_serializing_if = "Option::is_none")]
        pub r#metafile_format: Option<HtmlSaveOptionsData_MetafileFormatEnum>,


        /// Gets or sets the option that controls how OfficeMath objects are exported to HTML, MHTML or EPUB. The default value is HtmlOfficeMathOutputMode.Image.
        #[serde(rename = "OfficeMathOutputMode", skip_serializing_if = "Option::is_none")]
        pub r#office_math_output_mode: Option<HtmlSaveOptionsData_OfficeMathOutputModeEnum>,


        /// Gets or sets a value indicating whether to use pretty formats output.
        #[serde(rename = "PrettyFormat", skip_serializing_if = "Option::is_none")]
        pub r#pretty_format: Option<bool>,


        /// Gets or sets the flag that indicates whether JavaScript will be removed from links.
            /// Default is false.
            /// If this option is enabled, all links containing JavaScript (e.g., links with "javascript:" in the href attribute)
            /// will be replaced with "javascript:void(0)". This can help prevent potential security risks, such as XSS attacks.
        #[serde(rename = "RemoveJavaScriptFromLinks", skip_serializing_if = "Option::is_none")]
        pub r#remove_java_script_from_links: Option<bool>,


        /// Gets or sets the flag that indicates whether backslash characters should be replaced with yen signs.
            /// The default value is false.
            /// By default, Aspose.Words mimics MS Word's behavior and doesn't replace backslash characters with yen signs in
            /// generated HTML documents. However, previous versions of Aspose.Words performed such replacements in certain
            /// scenarios. This flag enables backward compatibility with previous versions of Aspose.Words.
        #[serde(rename = "ReplaceBackslashWithYenSign", skip_serializing_if = "Option::is_none")]
        pub r#replace_backslash_with_yen_sign: Option<bool>,


        /// Gets or sets a value indicating whether font family names used in the document are resolved and substituted according to FontSettings when being written into HTML-based formats.
            /// The default value is false.
        #[serde(rename = "ResolveFontNames", skip_serializing_if = "Option::is_none")]
        pub r#resolve_font_names: Option<bool>,


        /// Gets or sets the physical folder where all resources like images, fonts, and external CSS are saved when a document is exported to HTML. The default value is an empty string.
        #[serde(rename = "ResourceFolder", skip_serializing_if = "Option::is_none")]
        pub r#resource_folder: Option<String>,


        /// Gets or sets the name of the folder used to construct URIs of all resources written into HTML document. The default value is an empty string.
        #[serde(rename = "ResourceFolderAlias", skip_serializing_if = "Option::is_none")]
        pub r#resource_folder_alias: Option<String>,


        /// Gets or sets a value indicating whether images are scaled by Aspose.Words to the bounding shape size when exporting.
        #[serde(rename = "ScaleImageToShapeSize", skip_serializing_if = "Option::is_none")]
        pub r#scale_image_to_shape_size: Option<bool>,


        /// Gets or sets the option that controls how table, row and cell widths are exported.
        #[serde(rename = "TableWidthOutputMode", skip_serializing_if = "Option::is_none")]
        pub r#table_width_output_mode: Option<HtmlSaveOptionsData_TableWidthOutputModeEnum>,


}

impl Default for HtmlSaveOptionsData {
    fn default() -> Self {
        let mut parent = SaveOptionsData::default();
        parent.r#save_format = Some("html".to_owned());
        Self {
            parent,
            r#allow_negative_indent: None,
            r#css_class_name_prefix: None,
            r#css_style_sheet_file_name: None,
            r#css_style_sheet_type: None,
            r#document_split_criteria: None,
            r#document_split_heading_level: None,
            r#encoding: None,
            r#export_document_properties: None,
            r#export_drop_down_form_field_as_text: None,
            r#export_font_resources: None,
            r#export_fonts_as_base64: None,
            r#export_headers_footers_mode: None,
            r#export_images_as_base64: None,
            r#export_language_information: None,
            r#export_list_labels: None,
            r#export_original_url_for_linked_images: None,
            r#export_page_margins: None,
            r#export_page_setup: None,
            r#export_relative_font_size: None,
            r#export_roundtrip_information: None,
            r#export_text_input_form_field_as_text: None,
            r#export_toc_page_numbers: None,
            r#export_xhtml_transitional: None,
            r#font_resources_subsetting_size_threshold: None,
            r#fonts_folder: None,
            r#fonts_folder_alias: None,
            r#html_version: None,
            r#image_resolution: None,
            r#images_folder: None,
            r#images_folder_alias: None,
            r#metafile_format: None,
            r#office_math_output_mode: None,
            r#pretty_format: None,
            r#remove_java_script_from_links: None,
            r#replace_backslash_with_yen_sign: None,
            r#resolve_font_names: None,
            r#resource_folder: None,
            r#resource_folder_alias: None,
            r#scale_image_to_shape_size: None,
            r#table_width_output_mode: None,

        }
    }
}

impl Deref for HtmlSaveOptionsData {
    type Target = SaveOptionsData;

    fn deref(&self) -> &Self::Target {
        &self.parent
    }
}

impl DerefMut for HtmlSaveOptionsData {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.parent
    }
}

impl Model for HtmlSaveOptionsData {
    fn validate(&self) -> SdkResult<()> {
        self.parent.validate()?;
        Ok(())
    }

    fn collect_file_references<'a>(&'a self, output: &mut Vec<&'a FileReference>) {
        self.parent.collect_file_references(output);
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}

/// Gets or sets the option that controls how the CSS styles are exported.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HtmlSaveOptionsData_CssStyleSheetTypeEnum {
    #[serde(rename = "Inline")]
        Inline,
    #[serde(rename = "Embedded")]
        Embedded,
    #[serde(rename = "External")]
        External,
}

/// Gets or sets the option that controls how the document should be split when saving.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HtmlSaveOptionsData_DocumentSplitCriteriaEnum {
    #[serde(rename = "None")]
        None,
    #[serde(rename = "PageBreak")]
        PageBreak,
    #[serde(rename = "ColumnBreak")]
        ColumnBreak,
    #[serde(rename = "SectionBreak")]
        SectionBreak,
    #[serde(rename = "HeadingParagraph")]
        HeadingParagraph,
}

/// Gets or sets the option that controls how headers and footers are exported.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HtmlSaveOptionsData_ExportHeadersFootersModeEnum {
    #[serde(rename = "None")]
        None,
    #[serde(rename = "PerSection")]
        PerSection,
    #[serde(rename = "FirstSectionHeaderLastSectionFooter")]
        FirstSectionHeaderLastSectionFooter,
    #[serde(rename = "FirstPageHeaderFooterPerSection")]
        FirstPageHeaderFooterPerSection,
}

/// Gets or sets the option that controls how list labels are exported.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HtmlSaveOptionsData_ExportListLabelsEnum {
    #[serde(rename = "Auto")]
        Auto,
    #[serde(rename = "AsInlineText")]
        AsInlineText,
    #[serde(rename = "ByHtmlTags")]
        ByHtmlTags,
}

/// Gets or sets the version of HTML standard, that should be used when saving the document to HTML or MHTML.
/// The default value is Aspose.Words.Saving.HtmlVersion.Xhtml.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HtmlSaveOptionsData_HtmlVersionEnum {
    #[serde(rename = "Xhtml")]
        Xhtml,
    #[serde(rename = "Html5")]
        Html5,
}

/// Gets or sets the options, that controls in what format metafiles are saved when exporting to HTML, MHTML, or EPUB.
/// The default value is Aspose.Words.Saving.HtmlMetafileFormat.Png, meaning that metafiles are rendered to raster PNG images.
/// Metafiles are not natively displayed by HTML browsers. By default, Aspose.Words converts WMF and EMF images into PNG files when exporting to HTML.Other options are to convert metafiles to SVG images or to export them as is without conversion.
/// Some image transforms, in particular image cropping, will not be applied to metafile images if they are exported to HTML without conversion.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HtmlSaveOptionsData_MetafileFormatEnum {
    #[serde(rename = "Png")]
        Png,
    #[serde(rename = "Svg")]
        Svg,
    #[serde(rename = "EmfOrWmf")]
        EmfOrWmf,
}

/// Gets or sets the option that controls how OfficeMath objects are exported to HTML, MHTML or EPUB. The default value is HtmlOfficeMathOutputMode.Image.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HtmlSaveOptionsData_OfficeMathOutputModeEnum {
    #[serde(rename = "Image")]
        Image,
    #[serde(rename = "MathML")]
        MathML,
    #[serde(rename = "Text")]
        Text,
}

/// Gets or sets the option that controls how table, row and cell widths are exported.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HtmlSaveOptionsData_TableWidthOutputModeEnum {
    #[serde(rename = "All")]
        All,
    #[serde(rename = "RelativeOnly")]
        RelativeOnly,
    #[serde(rename = "None")]
        None,
}